### ISSUE TITLE
support MIPS

### ISSUE THREAD

**Issue by dummys** [nologic/idaref#2]
Hi,  very interesting plugin. Thanks. 
Did you plan to add MIPS ?  If not,  can you share your script to create  the database from intel arch ?

**Comment by nologic** [comment]
I was thinking about it, since a few people mentioned it. But, haven't had the time yet. Check out this repo: https://github.com/nologic/x86doc sorry, it's not as clean as the idaref. Your best best it to look at what I did for arm. I used some online service to convert PDF to Text then massage the output into an SQLite database. Ask if you have more questions.
